// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EdenTokenSystem } from "../../systems/EdenTokenSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type EdenTokenSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "GardenOfEden", name: "EdenTokenSystem" }))
EdenTokenSystemType constant edenTokenSystem = EdenTokenSystemType.wrap(
  0x737947617264656e4f664564656e00004564656e546f6b656e53797374656d00
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title EdenTokenSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library EdenTokenSystemLib {
  error EdenTokenSystemLib_CallingFromRootSystem();

  function systemMint(EdenTokenSystemType self, address to, uint256 amount) internal {
    return CallWrapper(self.toResourceId(), address(0)).systemMint(to, amount);
  }

  function systemBurn(EdenTokenSystemType self, address from, uint256 amount) internal {
    return CallWrapper(self.toResourceId(), address(0)).systemBurn(from, amount);
  }

  function systemTransfer(EdenTokenSystemType self, address from, address to, uint256 amount) internal {
    return CallWrapper(self.toResourceId(), address(0)).systemTransfer(from, to, amount);
  }

  function balanceOf(EdenTokenSystemType self, address account) internal view returns (uint256 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).balanceOf(account);
  }

  function totalSupply(EdenTokenSystemType self) internal view returns (uint256 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).totalSupply();
  }

  function _msgSender(EdenTokenSystemType self) internal view returns (address __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0))._msgSender();
  }

  function _msgValue(EdenTokenSystemType self) internal view returns (uint256 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0))._msgValue();
  }

  function systemMint(CallWrapper memory self, address to, uint256 amount) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert EdenTokenSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_systemMint_address_uint256.systemMint, (to, amount));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function systemBurn(CallWrapper memory self, address from, uint256 amount) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert EdenTokenSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_systemBurn_address_uint256.systemBurn, (from, amount));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function systemTransfer(CallWrapper memory self, address from, address to, uint256 amount) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert EdenTokenSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _systemTransfer_address_address_uint256.systemTransfer,
      (from, to, amount)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function balanceOf(CallWrapper memory self, address account) internal view returns (uint256 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert EdenTokenSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_balanceOf_address.balanceOf, (account));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint256));
    }
  }

  function totalSupply(CallWrapper memory self) internal view returns (uint256 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert EdenTokenSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_totalSupply.totalSupply, ());
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint256));
    }
  }

  function _msgSender(CallWrapper memory self) internal view returns (address __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert EdenTokenSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(__msgSender._msgSender, ());
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (address));
    }
  }

  function _msgValue(CallWrapper memory self) internal view returns (uint256 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert EdenTokenSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(__msgValue._msgValue, ());
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint256));
    }
  }

  function systemMint(RootCallWrapper memory self, address to, uint256 amount) internal {
    bytes memory systemCall = abi.encodeCall(_systemMint_address_uint256.systemMint, (to, amount));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function systemBurn(RootCallWrapper memory self, address from, uint256 amount) internal {
    bytes memory systemCall = abi.encodeCall(_systemBurn_address_uint256.systemBurn, (from, amount));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function systemTransfer(RootCallWrapper memory self, address from, address to, uint256 amount) internal {
    bytes memory systemCall = abi.encodeCall(
      _systemTransfer_address_address_uint256.systemTransfer,
      (from, to, amount)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function balanceOf(RootCallWrapper memory self, address account) internal view returns (uint256 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_balanceOf_address.balanceOf, (account));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint256));
    }
  }

  function totalSupply(RootCallWrapper memory self) internal view returns (uint256 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_totalSupply.totalSupply, ());

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint256));
    }
  }

  function _msgSender(RootCallWrapper memory self) internal view returns (address __auxRet0) {
    bytes memory systemCall = abi.encodeCall(__msgSender._msgSender, ());

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (address));
    }
  }

  function _msgValue(RootCallWrapper memory self) internal view returns (uint256 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(__msgValue._msgValue, ());

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint256));
    }
  }

  function callFrom(EdenTokenSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(EdenTokenSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(EdenTokenSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(EdenTokenSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(EdenTokenSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (EdenTokenSystemType) {
    return EdenTokenSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(EdenTokenSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _systemMint_address_uint256 {
  function systemMint(address to, uint256 amount) external;
}

interface _systemBurn_address_uint256 {
  function systemBurn(address from, uint256 amount) external;
}

interface _systemTransfer_address_address_uint256 {
  function systemTransfer(address from, address to, uint256 amount) external;
}

interface _balanceOf_address {
  function balanceOf(address account) external;
}

interface _totalSupply {
  function totalSupply() external;
}

interface __msgSender {
  function _msgSender() external;
}

interface __msgValue {
  function _msgValue() external;
}

using EdenTokenSystemLib for EdenTokenSystemType global;
using EdenTokenSystemLib for CallWrapper global;
using EdenTokenSystemLib for RootCallWrapper global;
